spring.application.name=hello-sever

spring.datasource.url=jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl